WITH P AS (
SELECT
        LAT_N,
        ROW_NUMBER() OVER (ORDER BY LAT_N ASC) AS Row_N
    FROM STATION
    ORDER BY LAT_N ASC
)
SELECT ROUND(LAT_N, 4)
FROM P
WHERE Row_N = (SELECT (MAX(Row_N)+1)/2 from P)
